apiVersion: v1
kind: Service
metadata:
  name: payment-server
  namespace: hermes
spec:
  type: NodePort
  ports:
    - port: 9292
      targetPort: 9292
      nodePort: 9292
  selector:
    app: payment-server
