apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-server-config
  namespace: hermes
data:
  PORT: "9292"
  NODE_ENV: "production"
  MONGODB_USER: "MONGODB_USER_PLACEHOLDER"
  MONGODB_CLUSTER: "MONGODB_CLUSTER_PLACEHOLDER"
  MONGODB_DATABASE: "MONGODB_DATABASE_PLACEHOLDER"
